import { TProduct } from "@/types/product";

export const PRODUCTS: TProduct[] = [
  {
    title: "Yachu Hair Oil - For Dandruff",
    subtitle: "Regrowth For Dandruff Case",
    rating: 4.5,
    reviews: 120,
    price: 99.99,
    tag: "Bestseller",
    imageSrc: "/product/dandruff.png",
  },
  {
    title: "Yachu Hair Oil - For Hairfall",
    subtitle: "Regrowth For Hair Fall Case",
    rating: 4.5,
    reviews: 120,
    price: 99.99,
    tag: "Bestseller",
    imageSrc: "/product/hairfall.png",
  },
  {
    title: "Yachu Skil Oil - For baldness",
    subtitle: "Regrowth For Baldness Case",
    rating: 4.2,
    reviews: 80,
    price: 149.99,
    imageSrc: "/product/baldness.png",
  },
];

export const HERO_BEFORE_AFTER = [
  { before: "/before.jpeg", after: "/after.jpg" },
  { before: "/before.jpeg", after: "/after.jpg" },
];

export const INGREDIENTS = [
  "False Daisy (भृङ्गराज)",
  "Clove (ल्वंग)",
  "Rosemary (गुहमेहदि)",
  "Cinnamon (दालचिनी)",
  "Amala (अमला)",
  "Soap Berry (रिठा)",
  "Lemon (कागती)",
  "Walnuts (ओखर)",
  "Mustard (तोरी)",
  "Moringa (शितल चिनी)",
  "Curry Leaf (करी पत्ता)",
  "Yellow Mustard (पहेलो तोरी)",
  "Cardamom (सुकमेल)",
  "Neem Peel (निमको बोक्रा)",
  "Ginger (अदुवा)",
  "Almond (बदाम)",
  "Neem Leaf (नीमको पात)",
  "Bay Leaf (तेज पत्ता)",
  "Dry Turmeric (सुकेको बेसार)",
  "Fenugreek (मेथी)",
  "Starflower (चक्रफुल)",
  "Acacia-concinna (सिककार्य)",
  "Boerhaavia Diffusa (पुनर्नवा)",
  "Carom Seed (ज्वानो)",
  "Aloe vera (घ्युकुमारी)",
  "Water Hyssop (ब्रह्मी)",
  "Heena Powder (मेहेंदिको धुलो)",
  "Indigo Powder (नीलको धुलो)",
  "Avocado (एभोकाडो)",
  "Alo-weed (शंखपुस्पी)",
  "Coconut (नरिवल)",
  "Black Cumin (कालो जीरा)",
];
