export const INGREDIENTS = [
  { en: "False Daisy", np: "भृङ्गराज", emoji: "/ingredients/1 (1).png" },
  { en: "Clove", np: "ल्वंग", emoji: "/ingredients/1 (2).png" },
  { en: "Rosemary", np: "गुहमेहदि", emoji: "/ingredients/1 (3).png" },
  { en: "Cinnamon", np: "दालचिनी", emoji: "/ingredients/1 (4).png" },
  { en: "Amala", np: "अमला", emoji: "/ingredients/1 (5).png" },
  { en: "Soap Berry", np: "रिठा", emoji: "/ingredients/1 (6).png" },
  { en: "Lemon", np: "कागती", emoji: "/ingredients/1 (7).png" },
  { en: "Walnuts", np: "ओखर", emoji: "/ingredients/1 (8).png" },
  { en: "Mustard", np: "तोरी", emoji: "/ingredients/1 (9).png" },
  { en: "Moringa", np: "शितल चिनी", emoji: "/ingredients/1 (10).png" },
  { en: "Curry Leaf", np: "करी पत्ता", emoji: "/ingredients/1 (11).png" },
  { en: "Yellow Mustard", np: "पहेलो तोरी", emoji: "/ingredients/1 (12).png" },
  { en: "Cardamom", np: "सुकमेल", emoji: "/ingredients/1 (13).png" },
  { en: "Neem Peel", np: "निमको बोक्रा", emoji: "/ingredients/1 (14).png" },
  { en: "Ginger", np: "अदुवा", emoji: "/ingredients/1 (15).png" },
  { en: "Almond", np: "बदाम", emoji: "/ingredients/1 (16).png" },
  { en: "Neem Leaf", np: "नीमको पात", emoji: "/ingredients/1 (17).png" },
  { en: "Bay Leaf", np: "तेज पत्ता", emoji: "/ingredients/1 (18).png" },
  { en: "Dry Turmeric", np: "सुकेको बेसार", emoji: "/ingredients/1 (19).png" },
  { en: "Fenugreek", np: "मेथी", emoji: "/ingredients/1 (20).png" },
  { en: "Starflower", np: "चक्रफुल", emoji: "/ingredients/1 (21).png" },
  { en: "Acacia concinna", np: "सिककार्य", emoji: "/ingredients/1 (22).png" },
  {
    en: "Boerhaavia Diffusa",
    np: "पुनर्नवा",
    emoji: "/ingredients/1 (23).png",
  },
  { en: "Carom Seed", np: "ज्वानो", emoji: "/ingredients/1 (24).png" },
  { en: "Aloe vera", np: "घ्युकुमारी", emoji: "/ingredients/1 (25).png" },
  { en: "Water Hyssop", np: "ब्रह्मी", emoji: "/ingredients/1 (26).png" },
  {
    en: "Heena Powder",
    np: "मेहेंदिको धुलो",
    emoji: "/ingredients/1 (27).png",
  },
  { en: "Indigo Powder", np: "नीलको धुलो", emoji: "/ingredients/1 (28).png" },
  { en: "Avocado", np: "एभोकाडो", emoji: "/ingredients/1 (29).png" },
  { en: "Alo-weed", np: "शंखपुस्पी", emoji: "/ingredients/1 (30).png" },
  { en: "Coconut", np: "नरिवल", emoji: "/ingredients/1 (31).png" },
  { en: "Black Cumin", np: "कालो जीरा", emoji: "/ingredients/1 (32).png" },
  { en: "Onion Seed", np: "प्याजको बीउ", emoji: "/ingredients/1 (7).png" },
];
